"""Property-based laws of the reversible lane (snapshot / apply / restore).

These do not pin scenarios — they assert the *algebra* of the journal fold over
arbitrary programs generated by Hypothesis:

- **rollback ≈ identity** — folding the journal forward then backward leaves the
  world byte-identical to the committed baseline, for any program.
- **commit is the forward fold** — after a clean commit the world equals the
  baseline with every operation applied in order (all-or-nothing: the whole
  program lands).
- **a mid-program failure rolls the whole txn back** — even a partial write by
  the failing effect is undone (snapshot precedes apply).

The world is the *real* :class:`SQLiteAdapter` over an in-memory ``kv`` table,
so it is production savepoint machinery being folded, not a toy.
"""

from __future__ import annotations

import pytest
from hypothesis import HealthCheck, given, settings

from pherix.core.adapters.sql import SQLiteAdapter
from pherix.core.effects import EffectStatus
from pherix.core.runtime import agent_txn
from pherix.core.tools import tool
from pherix.core.transaction import TxnState

from tests._laws import dump_kv, fresh_kv_conn, kv_programs, seed_programs

# The tool registry and these fixtures live for the whole test function;
# Hypothesis re-runs the body many times against them, so the fixture must not
# be reset per example — that is exactly what this health check guards, and
# here the non-reset is intentional (tools are immutable across examples).
_LAW = settings(
    max_examples=200,
    deadline=None,
    suppress_health_check=[HealthCheck.function_scoped_fixture],
)


@pytest.fixture
def kv_tools():
    """Register the fixed reversible toolset once for the whole test function."""

    @tool(resource="sql")
    def kv_set(conn, k, v):
        conn.execute(
            "INSERT INTO kv (k, v) VALUES (?, ?) "
            "ON CONFLICT(k) DO UPDATE SET v = excluded.v",
            (k, v),
        )
        return v

    @tool(resource="sql")
    def kv_del(conn, k):
        conn.execute("DELETE FROM kv WHERE k = ?", (k,))

    return kv_set, kv_del


def _run(tools, prog):
    """Drive a generated program through the registered tool wrappers."""
    kv_set, kv_del = tools
    for op in prog:
        if op.op == "set":
            kv_set(k=op.key, v=op.value)
        else:
            kv_del(k=op.key)


def _reference(state: dict[str, int], prog) -> dict[str, int]:
    """The world a clean commit must produce — the program applied to a dict."""
    out = dict(state)
    for op in prog:
        if op.op == "set":
            out[op.key] = op.value
        else:
            out.pop(op.key, None)
    return out


def _seed(conn, seed: dict[str, int]) -> None:
    for k, v in seed.items():
        conn.execute("INSERT INTO kv (k, v) VALUES (?, ?)", (k, v))


@given(seed=seed_programs(), prog=kv_programs())
@_LAW
def test_rollback_is_identity(kv_tools, seed, prog):
    """rollback ∘ (apply*) = identity on committed world state, any program."""
    conn = fresh_kv_conn()
    try:
        _seed(conn, seed)
        before = dump_kv(conn)
        with agent_txn({"sql": SQLiteAdapter(conn)}) as txn:
            _run(kv_tools, prog)
            txn.rollback()
        assert dump_kv(conn) == before
        assert txn.txn.state is TxnState.ROLLED_BACK
        # The backward fold visited every applied effect: each reversible
        # effect lands COMPENSATED, never half-undone.
        assert all(
            e.status is EffectStatus.COMPENSATED for e in txn.txn.effects
        )
    finally:
        conn.close()


@given(seed=seed_programs(), prog=kv_programs())
@_LAW
def test_commit_is_the_forward_fold(kv_tools, seed, prog):
    """A clean commit lands the whole program — all-or-nothing forward."""
    conn = fresh_kv_conn()
    try:
        _seed(conn, seed)
        before = dump_kv(conn)
        with agent_txn({"sql": SQLiteAdapter(conn)}) as txn:
            _run(kv_tools, prog)
        assert dump_kv(conn) == _reference(before, prog)
        assert txn.txn.state is TxnState.COMMITTED
        assert all(e.status is EffectStatus.APPLIED for e in txn.txn.effects)
    finally:
        conn.close()


@pytest.fixture
def boom_tool():
    """A reversible tool that writes then raises — registered once per function."""

    @tool(resource="sql")
    def kv_set_then_boom(conn, k, v):
        conn.execute(
            "INSERT INTO kv (k, v) VALUES (?, ?) "
            "ON CONFLICT(k) DO UPDATE SET v = excluded.v",
            (k, v),
        )
        raise RuntimeError("tool exploded after writing")

    return kv_set_then_boom


@given(seed=seed_programs(), prog=kv_programs(min_size=1))
@_LAW
def test_exception_mid_program_rolls_back_whole_txn(kv_tools, boom_tool, seed, prog):
    """An exception after some applied effects unwinds the *entire* txn.

    The failing effect itself writes before it raises; because snapshot
    precedes apply, even that partial write is restored — the world returns to
    the committed baseline, never to a partial state.
    """
    conn = fresh_kv_conn()
    try:
        _seed(conn, seed)
        before = dump_kv(conn)
        with pytest.raises(RuntimeError, match="exploded"):
            with agent_txn({"sql": SQLiteAdapter(conn)}) as txn:
                _run(kv_tools, prog)
                boom_tool(k="a", v=999)
        assert dump_kv(conn) == before
        assert txn.txn.state is TxnState.ROLLED_BACK
    finally:
        conn.close()
