"""Pherix — a transactional resource runtime for AI agents."""

from pherix.frontends.library import (
    Abort,
    Allow,
    AuditJournal,
    Broker,
    Cap,
    CompensatorNotRegistered,
    Conflict,
    Deny,
    DryRunResult,
    EffectOutcome,
    FilesystemAdapter,
    GateBlocked,
    HTTPAdapter,
    IrreversibleAdapterError,
    IsolationConflict,
    JournalRegistry,
    MongoAdapter,
    MQAdapter,
    MySQLAdapter,
    Policy,
    PolicyContext,
    PolicyRule,
    PolicyVerdict,
    PolicyViolation,
    PostgresAdapter,
    RedisAdapter,
    ReplayDivergence,
    ReplayResult,
    ResourceAdapter,
    RESTAdapter,
    Retry,
    S3Adapter,
    Serialize,
    SnapshotHandle,
    SQLiteAdapter,
    StagedResult,
    TransactionalResourceAdapter,
    VersionedResourceAdapter,
    agent_txn,
    dry_run,
    graphql_tool,
    publish_tool,
    replay,
    rest_tool,
    run_txn,
    tombstone_compensator,
    tool,
)

# The MCP gateway front-end (Slice 8) lives in its own package and surfaces at
# the top level directly — it is a second *driver* of the engine, parallel to
# the library API, not part of it. Importing from ``pherix.frontends.proxy``
# (rather than re-exporting through ``library``) keeps the gateway's
# dependency edge explicit: it is a front-end, peer to ``library``.
from pherix.frontends.proxy import (
    InProcessMCPClient,
    MCPClientError,
    MCPServer,
    PherixGateway,
    serve_stdio,
)

__all__ = [
    "agent_txn",
    "run_txn",
    "replay",
    "dry_run",
    "DryRunResult",
    "ReplayResult",
    "ReplayDivergence",
    "EffectOutcome",
    "tool",
    "Policy",
    "PolicyContext",
    "PolicyRule",
    "PolicyVerdict",
    "PolicyViolation",
    "Allow",
    "Deny",
    "Cap",
    "SQLiteAdapter",
    "FilesystemAdapter",
    "HTTPAdapter",
    "PostgresAdapter",
    "MySQLAdapter",
    "MongoAdapter",
    "S3Adapter",
    "RedisAdapter",
    "RESTAdapter",
    "rest_tool",
    "graphql_tool",
    "MQAdapter",
    "Broker",
    "publish_tool",
    "tombstone_compensator",
    "AuditJournal",
    "ResourceAdapter",
    "TransactionalResourceAdapter",
    "VersionedResourceAdapter",
    "SnapshotHandle",
    "StagedResult",
    "GateBlocked",
    "CompensatorNotRegistered",
    "IrreversibleAdapterError",
    "Abort",
    "Retry",
    "Serialize",
    "IsolationConflict",
    "Conflict",
    "JournalRegistry",
    "PherixGateway",
    "MCPServer",
    "InProcessMCPClient",
    "MCPClientError",
    "serve_stdio",
]
